TeamFunxtion/fx-frontend

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/fix.md, src/app/(products)/products/[id]/edit/page.tsx, src/app/(products)/products/new/page.tsx, src/components/products/ProductsNewForm.module.css, src/components/products/ProductsNewForm.tsx
>  #5 
> 상품 등록,수정화면 퍼블리싱 하였음.
>
=> Feature/#5 상품 등록,수정화면 퍼블리싱 

src/app/(talks)/talks/exist/layout.module.css, src/app/(talks)/talks/exist/layout.tsx, src/app/(talks)/talks/exist/page.module.css, src/app/(talks)/talks/exist/page.tsx, src/app/(talks)/talks/none/layout.module.css, src/app/(talks)/talks/none/layout.tsx, src/app/(talks)/talks/none/page.tsx
> #7
> 1대1 채팅방 UI 그리기 작업
> src\app\talks 경로에 대화중인 채팅방이 없는 경우 \none으로, 대화중인 채팅방이 있는 경우 \exist로 가게 설정해 놨는데, 이게 맞나요?
=> [#7] Design : 1대1 채팅방 UI 디자인

src/app/(notice)/notice/page.module.css, src/app/(notice)/notice/page.tsx
=> [#8] style : 공지사항화면 디자인

src/app/(auth)/auth/join/page.tsx, src/app/(shop)/shop/update/page.module.css, src/app/(shop)/shop/update/page.tsx, src/components/shop/shop-menubar.tsx
[#6] 내 정보 수정 퍼블리싱
내 정보 라우터 추가
내 정보수정 퍼블리싱
내 정보 수정 퍼블리싱 완료했습니다.
>
=> [#6] Feat : 내정보수정 퍼블리싱

src/app/(shop)/shop/follower/page.module.css, src/app/(shop)/shop/follower/page.tsx, src/app/(shop)/shop/following/page.module.css, src/app/(shop)/shop/following/page.tsx, src/components/header/header.tsx, src/components/shop/followCard.tsx, src/components/shop/followCart.module.css, src/components/shop/shop-info.tsx, src/components/shop/shop-menubar.tsx
팔로우/팔로워 목록 화면 퍼블리싱
> ex) #22 
> 팔로우/팔로워 목록 화면 라우터 추가 및 퍼블리싱
>
=> [#22] Design : 팔로우/팔로워 목록

package-lock.json, package.json, src/app/(chats)/chats/[id]/page.module.css, src/app/(chats)/chats/[id]/page.tsx, src/components/chats/Chats.tsx, src/components/products/ProductDetailInfo.tsx
> ex) #37-2
> 채팅방 생성& 실시간 채팅 구현
>
=> Feature/#37-2 

package-lock.json, src/app/(chats)/chats/[id]/page.module.css, src/app/(chats)/chats/[id]/page.tsx, src/app/(chats)/chats/layout.tsx, src/components/chats/Chats.tsx
> ex) #50
> 안전결제 버튼 & 메시지 구현
>
=> Feature/#50 안전결제 버튼 & 메시지 구현

package-lock.json, src/app/(shop)/shop/follower/page.tsx, src/app/(shop)/shop/following/page.tsx, src/components/shop/followCard.tsx
> #64 
> 팔로우/팔로잉 목록 페이징 처리(무한 스크롤로) 구현
>
=> [#64] 팔로우/팔로잉 목록 페이징 처리(무한 스크롤로) 구현

src/app/(chats)/chats/[id]/page.tsx, src/components/chats/Chats.tsx, src/store/atoms.js
> ex) #70 
> 1대1 채팅방 마지막 메시지 / 날짜 표시 기능
>
=> [#70] Feat 1대1 채팅방 마지막 메시지 / 날짜 표시 기능

src/app/(notice)/notice/[id]/edit/page.tsx, src/app/(notice)/notice/new/page.tsx, src/app/(notice)/notice/page.module.css, src/app/(notice)/notice/page.tsx, src/app/qna/qnainquiry/qnainquiryhistory.tsx
#72
공지사항 필수값체크, 비어있을시 메시지, 타이틀 입력안되는 버그 수정
>
=> [#72] Fix 공지사항 필수값체크, 비어있을시 메시지, 타이틀 입력안되는 버그 수정

src/app/(notice)/notice/new/page.module.css, src/app/qna/page.module.css, src/app/qna/page.tsx, src/app/qna/qnainquiry/qnainquiry.tsx, src/app/qna/qnainquiry/qnainquiryhistory.tsx, src/app/qna/qnainquiry/qnamanagerhistory.tsx
#69
공지사항 답변 기능 추가 및 게시글 0개일시 문구 추가
>
=> [#69] 공지사항 답변 기능 추가 및 게시글 0개일시 문구 추가

src/app/qna/page.module.css, src/app/qna/qnainquiry/qnainquiryhistory.tsx, src/app/qna/qnainquiry/qnamanagerhistory.tsx
#78
1:1 문의 답변완료,미등록 표시되도록 변경
>
=> [#78] 1:1 문의 답변완료,미등록 표시되도록 변경

src/app/(shop)/shop/[id]/favorites/page.module.css, src/app/(shop)/shop/[id]/favorites/page.tsx
> ex) #80
> 관심상품 목록 퍼블리싱 / 조회 / 추가&삭제
>
=> [#80] Feat : 관심상품 목록 퍼블리싱 / 조회 / 추가&삭제

src/app/(shop)/shop/[id]/auctions/page.module.css, src/app/(shop)/shop/[id]/auctions/page.tsx, src/app/(shop)/shop/[id]/bids/page.module.css, src/app/(shop)/shop/[id]/bids/page.tsx, src/app/constants.ts
=> Feature/#83 진행,판매중 경매 퍼블리싱&기능구현

src/app/(chats)/chats/[id]/page.tsx, src/components/chats/Chats.tsx
=> [#90] 상품 이미지 채팅방에 적용

src/app/(shop)/shop/[id]/buy/page.tsx, src/app/(shop)/shop/[id]/sell/page.tsx, src/app/qna/qnainquiry/qnamanagerhistory.tsx, src/components/etc/etcsidebar.tsx
=> [#81] Feat 판매내역,구매내역 프론트 구현

src/app/(chats)/chats/[id]/page.tsx
> ex) #95 
> 1대1 채팅 메시지 공백 못보내게 수정
>
=> [Fix] #95 1대1 채팅 메시지 공백 못보내게 수정

src/app/(chats)/chats/[id]/page.tsx
=> [fix] #100 채팅방 관련 오류들 수정

src/app/(chats)/chats/[id]/page.tsx, src/app/(shop)/shop/[id]/favorites/page.module.css, src/app/(shop)/shop/[id]/favorites/page.tsx, src/app/(shop)/shop/[id]/follower/page.tsx, src/app/(shop)/shop/[id]/following/page.tsx, src/components/chats/Chats.tsx, src/components/shop/followCard.tsx
> ex) #104 
> 채팅방/ 팔로우/팔로잉 오류 수정 (testcode  오류 내용 기반)
>
=> Fix/#104 채팅방/ 팔로우/팔로잉 오류 수정

src/app/(shop)/shop/[id]/profile/page.tsx
#99 
회원정보수정 비밀번호, 회원탈퇴 기능 수정
>
=> Fix/#99 회원정보수정 비밀번호, 회원탈퇴 기능 수정

src/app/(shop)/shop/[id]/profile/page.tsx
#108 
회원정보수정 새비밀번호, 새비밀번호 확인 문구 기능수정 및 회원탈퇴 기능 탈퇴 성공시 로그아웃, 홈화면 리다이렉트 기능 
>
=> [#108] Fix : 회원정보수정 새비밀번호, 새비밀번호 확인 및 회원탈퇴 기능 수정

src/app/(notice)/notice/new/page.tsx, src/app/(shop)/shop/[id]/buy/page.tsx, src/app/(shop)/shop/[id]/sell/page.tsx, src/app/qna/qnainquiry/qnainquiry.tsx, src/components/atom/MRadio.tsx
#110
Fix 공백입력시 등록가능했던 버그 수정, 판매,구매내역 가격 오류 수정 
>
=> [#110] Fix 공백입력시 등록가능했던 버그 수정, 판매,구매내역 가격 오류 수정 

src/app/qna/qnainquiry/qnamanagerhistory.tsx
=> #113 Fix 답변에 공백 입력 불가능하게 변경

src/app/(shop)/shop/[id]/profile/page.module.css, src/app/(shop)/shop/[id]/profile/page.tsx
#112 
비밀번호 오류메세지 초록->빨강, 소개글 textarea 부분 css 수정
>
=> [#112] Fix : 비밀번호 오류메세지 초록->빨강, 소개글 textarea 부분 css 수정

src/app/(notice)/notice/page.module.css, src/app/(notice)/notice/page.tsx
=> [#117] 공지사항 css 수정

src/app/(chats)/chats/[id]/page.module.css, src/app/(chats)/chats/[id]/page.tsx, src/app/(chats)/chats/layout.module.css, src/components/chats/Chats.tsx
=> [fix] #121 채팅방 css 수정

src/app/(chats)/chats/[id]/page.tsx, src/components/chats/Chats.tsx, src/store/atoms.js
> ex) #123 
>채팅방 새로고침 버튼 기능 구현
>
=> [#feat] 123 채팅방 새로고침 버튼 기능 구현

src/app/(notice)/notice/page.module.css
=> [#125] Fix 공지사항 글자 이상 해결

src/app/(chats)/chats/[id]/page.module.css, src/app/(chats)/chats/[id]/page.tsx
=> [fix] 127 채팅방 버튼 css 수정

src/app/(chats)/chats/[id]/page.tsx, src/app/(chats)/chats/layout.module.css, src/components/chats/Chats.tsx, src/store/atoms.js
> ex) #129 
> 대화 상대방이 판매자인지, 구매자인지 표시+ 새로고침 버튼 버그 수정
>
=> [feat, fix] 대화 상대방이 판매자인지, 구매자인지 표시+ 새로고침 버튼 버그 수정

src/components/etc/etcsidebar.module.css, src/components/etc/etcsidebar.tsx
[#131]
공지사항 사이드바 현재페이지에 맞춰 파란색으로 변경
>
=> [#131] Fix 공지사항 사이드바 현재페이지에 맞춰 파란색으로 변경

src/app/faq/edit/[id]/page.module.css, src/app/faq/edit/[id]/page.tsx, src/app/faq/page.module.css, src/app/faq/page.tsx
#119 
FAQ 새글 등록버튼 CSS 수정, FAQ 수정 화면 목록가기 버튼 추가 및 CSS 수정
>
=> [#119] Fix: FAQ 새글 등록버튼 CSS 수정, FAQ 수정 화면 목록가기 버튼 추가 및 CSS 수정

src/app/(chats)/chats/[id]/page.module.css, src/app/(chats)/chats/[id]/page.tsx, src/app/(chats)/chats/layout.module.css
> ex) #143 
>채팅방 테두리 선 css 수정
>
=> [fix]#143 채팅방 테두리 선 css 수정

src/app/faq/edit/[id]/page.tsx, src/app/faq/newfaq/page.tsx
#138 
fix : FAQ 새글 등록,수정 공백추가 X 기능 수정
>
=> [#138]fix : FAQ 새글 등록,수정 공백추가 X 기능 수정

src/app/(chats)/chats/[id]/page.tsx, src/app/(chats)/chats/layout.module.css, src/components/chats/Chats.tsx, src/components/shop/shop-info.module.css, src/components/shop/shop-info.tsx
> ex) #145 
> 마이페이지/게스트페이지 판매자 평점 표시
>
=> [feature] #145 마이페이지/게스트페이지 판매자 평점

src/app/(chats)/chats/layout.module.css, src/components/chats/Chats.tsx
=> [fix]148 채팅방 목록 css 수정

src/app/qna/page.module.css, src/app/qna/qnainquiry/qnamanagerhistory.tsx
=> [#149} 1:1문의 전체조회 미답변조회 기능 추가

src/app/(notice)/notice/[id]/edit/page.module.css, src/app/(notice)/notice/new/page.module.css, src/app/faq/edit/[id]/page.module.css, src/app/faq/edit/[id]/page.tsx, src/app/faq/newfaq/page.module.css, src/app/faq/newfaq/page.tsx, src/app/faq/page.module.css, src/app/faq/page.tsx, src/app/qna/page.module.css
#147 
faq 목록가기 버튼 수정 및 css 변경
>
=> [#147] fix : faq 목록가기 버튼 수정 및 css 변경

src/components/shop/shop-info.tsx
> ex) #154
> 평점 소수점 표시 제대로 되게 수정
>
=> [fix]#154 평점 소수점 표시 제대로 되게 수정

src/app/qna/qnainquiry/qnamanagerhistory.tsx
#156
답변 등록부분에 getList(currentPage); 추가하여 등록완료후 현재페이지로 새로고침
>
=> [#156] Fix 1:1문의 답변 오류 해결
